version: '3.1'

services:
  axonserver:
    image: axoniq/axonserver
    volumes:
      - ./axon-server-data:/eventdata
    environment:
      - AXONSERVER_HOSTNAME=axonserver
    ports:
      - 8024:8024
      - 8124:8124
    networks:
      - axon
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - axon

networks:
  axon:
    driver: bridge
