apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: axonserver
  name: axonserver
spec:
  ports:
  - name: "8024"
    port: 8024
    targetPort: 8024
  - name: "8124"
    port: 8124
    targetPort: 8124
  selector:
    io.kompose.service: axonserver
status:
  loadBalancer: {}
