@startuml
class User <<Aggregate>> {
  username: String
  password: String
  salt: String
  premium: Boolean
  tokenId: String
  accessToken: String
}
class UserId<<ValueObject>>{
  userId: UUID
}
UserId -* User
@enduml
