spring:
  application:
    name: Services
  data:
    mongodb:
      authentication-database: admin
      database: test_db
      host: localhost
      password: admin
      port: 27017
      username: admin

# Possible values for these keys are `default`, `xstream`, `java`, and `jackson`.
#axon:
#  serializer:
#    general: xstream #xstream is required to prevent errors recreating aggregates
#    events: jackson
#    messages: jackson


axoniq:
  axonserver:
    devmode:
      enabled: true

graphql:
  packages:
    - "club.piggyplanner.services"

server:
  port: 8181
