spring:
  data:
    mongodb:
      authentication-database: admin
      database: piggyplanner
      host: mongo
      password: admin
      port: 27017
      username: admin

axoniq:
  axonserver:
    devmode:
      enabled: false