spring:
  application:
    name: Services
  data:
    mongodb:
      authentication-database: admin
      database: piggyplanner
      host: localhost
      password: admin
      port: 27017
      username: admin

graphql:
  packages:
    - "club.piggyplanner.services"

server:
  port: 8181
