version: '3.1'

services:
  axonserver:
    image: axoniq/axonserver:4.4
#    volumes:
#      - ./axon-server/eventdata:/eventdata
#      - ./axon-server/data:/data
    environment:
      - AXONSERVER_HOSTNAME=axonserver
    ports:
      - 8024:8024
      - 8124:8124
    networks:
      - pigplan
  mongo:
    image: mongo
#    volumes:
#      - ./mongo-data:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - pigplan

networks:
  pigplan:
    driver: bridge
