name: build_master

on:
  push:
    branches:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run docker compose
        working-directory: ./platform/dev
        run: docker-compose up -d

      - name: Test and build
        working-directory: ./services
        run: ./gradlew build

  deploy-backend:
    runs-on: ubuntu-latest
    needs: [test-backend]

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker hub Registry
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend app and create docker image
        working-directory: ./services
        run: |
          export BUILD_VERSION=stage
          ./gradlew jib
